/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.FieldTheory.IsAlgClosed.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
import TauCeti.RingTheory.TensorProduct.PointSeparation
import TauCeti.RingTheory.FiniteType.PointSeparation
import Mathlib.RingTheory.Ideal.Quotient.Nilpotent

/-!
# The Hopf ideal vanishing on a subgroup of rational points

The functions vanishing on any subgroup of the rational points of an affine group form a
radical Hopf ideal. Its quotient is the reduced closed subgroup generated by those points.
No finite-type or algebraic-closedness assumption is needed. This construction connects
abstract point subgroups, such as commutator subgroups, with closed subgroup schemes.

## References

* W. C. Waterhouse, *Introduction to Affine Group Schemes*, §4.
-/

public section

open scoped TensorProduct
open WithConv

namespace TauCeti.HopfIdeal

noncomputable section

variable {k H : Type*} [Field k] [CommRing H] [HopfAlgebra k H]

/-- Functions vanishing at every point of the subgroup. -/
private def pointKernelIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) : Ideal H :=
  ⨅ g : S, RingHom.ker g.val.ofConv

private theorem mem_pointKernelIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) (x : H) :
    x ∈ pointKernelIdeal S ↔ ∀ g : S, g.val.ofConv x = 0 := by
  simp [pointKernelIdeal, RingHom.mem_ker]

/-- Evaluation at a subgroup point descends to the quotient by its vanishing ideal. -/
private def quotientEval (S : Subgroup (WithConv (H →ₐ[k] k))) (g : S) :
    H ⧸ pointKernelIdeal S →ₐ[k] k :=
  Ideal.Quotient.liftₐ _ g.val.ofConv fun x hx ↦ (mem_pointKernelIdeal S x).mp hx g

private theorem quotientEval_mk (S : Subgroup (WithConv (H →ₐ[k] k))) (g : S) (x : H) :
    quotientEval S g (Ideal.Quotient.mk (pointKernelIdeal S) x) = g.val.ofConv x :=
  Ideal.Quotient.liftₐ_apply _ _ _ _

private theorem quotientEval_separates (S : Subgroup (WithConv (H →ₐ[k] k)))
    (x : H ⧸ pointKernelIdeal S) (hx : ∀ g, quotientEval S g x = 0) : x = 0 := by
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mkₐ_surjective k (pointKernelIdeal S) x
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact (mem_pointKernelIdeal S x).mpr hx

private theorem comul_mem_pointKernelIdeal (S : Subgroup (WithConv (H →ₐ[k] k)))
    {x : H} (hx : x ∈ pointKernelIdeal S) :
    Coalgebra.comul (R := k) x ∈
      leftTensorIdeal (R := k) (H := H) (pointKernelIdeal S) ⊔
        rightTensorIdeal (R := k) (H := H) (pointKernelIdeal S) := by
  let q := Ideal.Quotient.mkₐ k (pointKernelIdeal S)
  have hker : RingHom.ker q = pointKernelIdeal S := Ideal.Quotient.mkₐ_ker k (pointKernelIdeal S)
  rw [← hker, ← ker_tensorProduct_map_eq_leftTensorIdeal_sup_rightTensorIdeal q q
    (Ideal.Quotient.mkₐ_surjective k _) (Ideal.Quotient.mkₐ_surjective k _), RingHom.mem_ker]
  apply tensor_eq_zero_of_forall_productMap_eq_zero
    (quotientEval S) (quotientEval S) (quotientEval_separates S) (quotientEval_separates S)
  intro g h
  have heq : (Algebra.TensorProduct.productMap (quotientEval S g) (quotientEval S h)).comp
      (Algebra.TensorProduct.map q q) =
        Algebra.TensorProduct.productMap g.val.ofConv h.val.ofConv := by
    ext : 1 <;> ext b <;> simp [AlgHom.comp_apply, q, quotientEval_mk]
  rw [← AlgHom.comp_apply, heq]
  exact (AlgHom.convMul_apply g.val h.val x).symm.trans
    ((mem_pointKernelIdeal S x).mp hx (g * h))

/-- The radical Hopf ideal of functions vanishing on a subgroup of rational points. -/
def vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) : HopfIdeal k H :=
  ofIdeal (pointKernelIdeal S) (fun _ hx ↦ comul_mem_pointKernelIdeal S hx)
    (fun x hx ↦ by simpa using (mem_pointKernelIdeal S x).mp hx 1)
    (fun x hx ↦ (mem_pointKernelIdeal S _).mpr fun g ↦ by
      simpa using (mem_pointKernelIdeal S x).mp hx g⁻¹)

/-- Membership means vanishing at every point of the subgroup. -/
@[simp]
theorem mem_vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) (x : H) :
    x ∈ vanishingIdeal S ↔ ∀ g : S, g.val.ofConv x = 0 :=
  mem_ofIdeal.trans (mem_pointKernelIdeal S x)

/-- The underlying ideal is the intersection of the kernels of the evaluations. -/
theorem vanishingIdeal_toIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) :
    (vanishingIdeal S).toIdeal = ⨅ g : S, RingHom.ker g.val.ofConv := by
  ext x
  rw [mem_toIdeal, mem_vanishingIdeal]
  simp [RingHom.mem_ker]

/-- The vanishing ideal of a point subgroup is radical. -/
theorem isRadical_vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) :
    (vanishingIdeal S).toIdeal.IsRadical := by
  rw [vanishingIdeal_toIdeal]
  exact Ideal.isRadical_iInf _ fun g ↦ (Ideal.isRadical_bot (R := k)).comap g.val.ofConv

/-- The closed subgroup cut out by the vanishing ideal of a point subgroup is reduced. -/
instance isReduced_quotient_vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) :
    IsReduced (CommHopfAlgCat.quotient (_root_.CommHopfAlgCat.of k H)
      (vanishingIdeal S)) := by
  rw [← Ideal.isRadical_iff_quotient_reduced]
  exact isRadical_vanishingIdeal S

/-- A Hopf ideal vanishes on a point subgroup exactly when the associated closed subgroup
contains that point subgroup. This is the minimality property of its closed subgroup closure. -/
theorem le_vanishingIdeal_iff (S : Subgroup (WithConv (H →ₐ[k] k))) (I : HopfIdeal k H) :
    I ≤ vanishingIdeal S ↔
      S ≤ CommHopfAlgCat.quotientPointsSubgroup (CommHopfAlgCat.of k H) I (CommAlgCat.of k k) := by
  constructor
  · intro h g hg
    apply (CommHopfAlgCat.mem_quotientPointsSubgroup_iff
      (_root_.CommHopfAlgCat.of k H) I (CommAlgCat.of k k) g).mpr
    intro x hx
    exact (mem_vanishingIdeal S x).mp (h hx) ⟨g, hg⟩
  · intro h x hx
    apply (mem_vanishingIdeal S x).mpr
    intro g
    exact (CommHopfAlgCat.mem_quotientPointsSubgroup_iff
      (_root_.CommHopfAlgCat.of k H) I (CommAlgCat.of k k) g.val).mp (h g.2) x hx

/-- The closure of the trivial point subgroup is the identity subgroup scheme. -/
@[simp] theorem vanishingIdeal_bot :
    vanishingIdeal (⊥ : Subgroup (WithConv (H →ₐ[k] k))) = augmentation k H := by
  ext x
  simp [mem_vanishingIdeal, mem_augmentation, AlgHom.convOne_apply]

/-- A point subgroup has trivial reduced closure exactly when it is trivial. -/
@[simp] theorem vanishingIdeal_eq_augmentation_iff
    (S : Subgroup (WithConv (H →ₐ[k] k))) :
    vanishingIdeal S = augmentation k H ↔ S = ⊥ := by
  constructor
  · intro h
    apply le_bot_iff.mp
    intro g hg
    apply Subgroup.mem_bot.mpr
    apply CommHopfAlgCat.eq_one_of_mem_quotientPointsSubgroup_augmentation
      (_root_.CommHopfAlgCat.of k H) (CommAlgCat.of k k)
    exact ((le_vanishingIdeal_iff S (augmentation k H)).mp h.ge) hg
  · rintro rfl
    exact vanishingIdeal_bot

/-- Rational points are schematically dense in a reduced finite-type affine group over an
algebraically closed field. -/
@[simp] theorem vanishingIdeal_top [IsAlgClosed k] [Algebra.FiniteType k H] [IsReduced H] :
    vanishingIdeal (⊤ : Subgroup (WithConv (H →ₐ[k] k))) = ⊥ := by
  apply le_bot_iff.mp
  intro x hx
  apply HopfIdeal.mem_bot.mpr
  apply eq_of_forall_algHom_apply_eq (k := k) (K := k)
  intro f
  exact ((mem_vanishingIdeal _ x).mp hx ⟨toConv f, Subgroup.mem_top _⟩).trans
    (map_zero f).symm

end

end TauCeti.HopfIdeal
