/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.RingTheory.Etale.Basic
public import TauCeti.RingTheory.Idempotents.Connected.Component

/-!
# Étale coordinate algebras of connected components

For a ring with locally connected prime spectrum, the quotient cutting out a connected
component is étale over the original ring. Thus a component of a smooth affine scheme is
again smooth. No reducedness or Noetherian hypothesis on the ring is needed.

The component ideal is generated by an idempotent. We use Mathlib's
`Algebra.FormallyEtale.iff_of_surjective` and the finite presentation of a quotient by a
finitely generated ideal.

## References

* The Stacks Project, Section 10.143, Étale ring maps.
-/

public section

namespace TauCeti

variable {R : Type*} [CommRing R] [LocallyConnectedSpace (PrimeSpectrum R)]

/-- The coordinate algebra of a connected component is étale over the ambient ring. -/
instance etale_quotient_connectedComponentIdeal (x : PrimeSpectrum R) :
    Algebra.Etale R (R ⧸ PrimeSpectrum.connectedComponentIdeal x) := by
  have hI : PrimeSpectrum.connectedComponentIdeal x =
      Ideal.span {1 - PrimeSpectrum.connectedComponentIdempotent x} := by
    ext r
    rw [PrimeSpectrum.mem_connectedComponentIdeal_iff, Ideal.mem_span_singleton']
  refine { formallyEtale := ?_, finitePresentation := ?_ }
  · apply (Algebra.FormallyEtale.iff_of_surjective Ideal.Quotient.mk_surjective).mpr
    rw [Ideal.Quotient.algebraMap_eq, Ideal.mk_ker, hI]
    simp only [IsIdempotentElem, Ideal.span_singleton_mul_span_singleton,
      (PrimeSpectrum.isIdempotentElem_connectedComponentIdempotent x).one_sub.eq]
  · apply Algebra.FinitePresentation.quotient
    rw [hI]
    exact Submodule.fg_span_singleton _

end TauCeti
