/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Coordinate.HopfAlgebra
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Dual
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Matrix
import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.FunctorOfPoints
import TauCeti.Algebra.HopfAlgebra.Basic

/-!
# The coordinate morphism of a finite free comodule

A right comodule over a commutative Hopf algebra `H` with a basis indexed by `Fin n` has a
coefficient matrix over `H`, whose determinant is a unit
(`TauCeti.Comodule.isUnit_det_coefficientMatrix`). Evaluation on that matrix therefore extends
from the matrix monoid coordinate ring to the coordinate ring of `GLₙ`, and the coalgebra
identities satisfied by the coefficient matrix say exactly that the extension is a morphism of
bialgebras

```text
O(GLₙ) ⟶ H.
```

This is the coordinate-ring morphism opposite to the representation of the affine group
represented by `H` on the chosen basis. Its surjectivity is the algebraic condition which the
faithful-representation criterion identifies with a closed immersion into `GLₙ`.

## Main declarations

* `TauCeti.Comodule.coordinateBialgHom`: the induced morphism `O(GLₙ) ⟶ H`.
* `TauCeti.Comodule.coordinateBialgHom_X`: the coordinate morphism sends the generic entry
  `Xᵢⱼ` to the corresponding coefficient-matrix entry.
* `TauCeti.Comodule.coordinateBialgHom_antipode_X`: its value on the antipode generators.
* `TauCeti.Comodule.coordinateBialgHom_range`: its image is the algebra generated by matrix
  coefficients and their antipode images.
* `TauCeti.Comodule.coordinateBialgHom_surjective_iff`: the corresponding generation criterion.

## References

This is the standard coordinate morphism of a finite free representation; see J. S.
Milne, *Algebraic Groups* (2017), Chapter 4, especially Remark 4.1 and Theorem 4.9.  It advances
`ReductiveGroups/README.md`, Layer 1, "Faithfulness done right".
-/

public section

open scoped TensorProduct
open Coalgebra Module WithConv

namespace TauCeti.Comodule

universe u v w

noncomputable section

section CoefficientMatrix

variable {R : Type u} {H : Type v} {M : Type w}
variable [CommSemiring R] [CommSemiring H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]

/-- Every coefficient-matrix entry belongs to the algebra generated by the coefficients and
their antipode images. -/
@[simp]
theorem coefficientMatrix_mem_matrixCoefficientSubalgebraWithAntipode
    {x : Type*} (b : Basis x R M) (i j : x) :
    coefficientMatrix (C := H) b i j ∈
      matrixCoefficientSubalgebraWithAntipode (R := R) (H := H) (M := M) := by
  rw [matrixCoefficientSubalgebraWithAntipode_def]
  exact (le_sup_left : matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ≤ _)
    (coefficientMatrix_mem_matrixCoefficientSubalgebra b i j)

/-- The antipode of every coefficient-matrix entry belongs to the algebra generated by the
coefficients and their antipode images. -/
@[simp]
theorem antipode_coefficientMatrix_mem_matrixCoefficientSubalgebraWithAntipode
    {x : Type*} (b : Basis x R M) (i j : x) :
    HopfAlgebra.antipode R (coefficientMatrix (C := H) b i j) ∈
      matrixCoefficientSubalgebraWithAntipode (R := R) (H := H) (M := M) := by
  rw [matrixCoefficientSubalgebraWithAntipode_def]
  apply (le_sup_right :
    (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
      (HopfAlgebra.antipodeAlgHom R H) ≤ _)
  exact ⟨coefficientMatrix (C := H) b i j,
    coefficientMatrix_mem_matrixCoefficientSubalgebra b i j, rfl⟩

end CoefficientMatrix

section Coordinate

variable {R : Type u} {H : Type v} {M : Type w}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]
variable {n : ℕ}

private def coordinateAlgHom (b : Basis (Fin n) R M) :
    GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] H :=
  (GeneralLinear.generalLinearToPoint (R := R) n
    (Matrix.GeneralLinearGroup.mk'' (coefficientMatrix (C := H) b)
      (isUnit_det_coefficientMatrix (C := H) b))).ofConv

@[simp]
private theorem coordinateAlgHom_X (b : Basis (Fin n) R M) (i j : Fin n) :
    coordinateAlgHom (H := H) b
        (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))) =
      coefficientMatrix (C := H) b i j := by
  simp only [coordinateAlgHom, GeneralLinear.generalLinearToPoint_apply,
    Matrix.GeneralLinearGroup.val_mk'']

private theorem coordinateAlgHom_counit (b : Basis (Fin n) R M) :
    (Bialgebra.counitAlgHom R H).comp (coordinateAlgHom (H := H) b) =
      Bialgebra.counitAlgHom R (GeneralLinear.coordinateHopfAlgebra R n) := by
  apply GeneralLinear.coordinateHopfAlgebra_algHom_ext R n
  intro i j
  simp only [AlgHom.comp_apply, Bialgebra.counitAlgHom_apply, coordinateAlgHom_X,
    counit_coefficientMatrix, GeneralLinear.coordinateHopfAlgebra_counit_X]

private theorem coordinateAlgHom_comul (b : Basis (Fin n) R M) :
    (Algebra.TensorProduct.map (coordinateAlgHom (H := H) b) (coordinateAlgHom (H := H) b)).comp
        (Bialgebra.comulAlgHom R (GeneralLinear.coordinateHopfAlgebra R n)) =
      (Bialgebra.comulAlgHom R H).comp (coordinateAlgHom (H := H) b) := by
  apply GeneralLinear.coordinateHopfAlgebra_algHom_ext R n
  intro i j
  simp only [AlgHom.comp_apply, Bialgebra.comulAlgHom_apply,
    GeneralLinear.coordinateHopfAlgebra_comul_X, map_sum,
    Algebra.TensorProduct.map_tmul, coordinateAlgHom_X]
  exact (comul_coefficientMatrix_eq_sum (C := H) b i j).symm

/-- The coordinate Hopf-algebra morphism associated to a comodule with a basis indexed by
`Fin n`.

Contravariantly, this is the morphism from the affine group represented by `H` to `GLₙ`
defined by the corresponding representation. -/
def coordinateBialgHom (b : Basis (Fin n) R M) :
    GeneralLinear.coordinateHopfAlgebra R n →ₐc[R] H :=
  BialgHom.ofAlgHom (coordinateAlgHom b) (coordinateAlgHom_counit b)
    (coordinateAlgHom_comul b)

/-- The coordinate Hopf-algebra morphism sends a generic matrix entry to the corresponding
coefficient-matrix entry. -/
@[simp]
theorem coordinateBialgHom_X (b : Basis (Fin n) R M) (i j : Fin n) :
    coordinateBialgHom (H := H) b
        (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))) =
      coefficientMatrix (C := H) b i j := by
  simp only [coordinateBialgHom, BialgHom.ofAlgHom_apply, coordinateAlgHom_X]

/-- The coordinate Hopf-algebra morphism sends an antipode generator of `O(GLₙ)` — an entry of
the inverse of the localized generic matrix — to the antipode of the corresponding
coefficient-matrix entry. -/
@[simp]
theorem coordinateBialgHom_antipode_X (b : Basis (Fin n) R M) (i j : Fin n) :
    coordinateBialgHom (H := H) b
        (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          ((GeneralLinear.localizedGenericMatrix R n)⁻¹ i j)) =
      HopfAlgebra.antipode R (coefficientMatrix (C := H) b i j) := by
  rw [← GeneralLinear.coordinateHopfAlgebra_antipode_X, BialgHomClass.map_antipode,
    coordinateBialgHom_X]

/-- The image of the coordinate morphism of a based finite free comodule is exactly the algebra
generated by its coefficients and their antipode images.

The original coefficients are the images of the generic matrix entries, while the antipode
images are the images of the inverse-matrix entries. -/
@[simp]
theorem coordinateBialgHom_range (b : Basis (Fin n) R M) :
    (coordinateBialgHom (H := H) b).toAlgHom.range =
      matrixCoefficientSubalgebraWithAntipode (R := R) (H := H) (M := M) := by
  classical
  apply le_antisymm
  · rw [← Algebra.map_top,
      ← GeneralLinear.adjoin_coordinateHopfAlgebra_X_union_antipode_X,
      AlgHom.map_adjoin]
    apply Algebra.adjoin_le
    rintro _ ⟨_, ⟨⟨i, j⟩, rfl⟩ | ⟨⟨i, j⟩, rfl⟩, rfl⟩
    · rw [BialgHom.coe_toAlgHom, coordinateBialgHom_X]
      exact coefficientMatrix_mem_matrixCoefficientSubalgebraWithAntipode (H := H) b i j
    · rw [BialgHom.coe_toAlgHom, BialgHomClass.map_antipode, coordinateBialgHom_X]
      exact antipode_coefficientMatrix_mem_matrixCoefficientSubalgebraWithAntipode
        (H := H) b i j
  · rw [matrixCoefficientSubalgebraWithAntipode_def]
    apply sup_le
    · rw [← adjoin_coefficientMatrixSet b]
      apply Algebra.adjoin_le
      intro c hc
      obtain ⟨i, j, rfl⟩ := (mem_coefficientMatrixSet_iff (C := H) b c).mp hc
      apply (AlgHom.mem_range
        (φ := (coordinateBialgHom (H := H) b).toAlgHom)).mpr
      refine ⟨GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
        (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j))), ?_⟩
      simpa only [BialgHom.coe_toAlgHom] using coordinateBialgHom_X (H := H) b i j
    · rw [← adjoin_coefficientMatrixSet b, AlgHom.map_adjoin]
      apply Algebra.adjoin_le
      intro c hc
      obtain ⟨d, hd, rfl⟩ := hc
      obtain ⟨i, j, rfl⟩ := (mem_coefficientMatrixSet_iff (C := H) b d).mp hd
      apply (AlgHom.mem_range
        (φ := (coordinateBialgHom (H := H) b).toAlgHom)).mpr
      refine ⟨GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
        ((GeneralLinear.localizedGenericMatrix R n)⁻¹ i j), ?_⟩
      simpa only [BialgHom.coe_toAlgHom, HopfAlgebra.antipodeAlgHom_apply] using
        coordinateBialgHom_antipode_X (H := H) b i j

/-- The coordinate morphism is surjective exactly when the coefficients and their antipode
images generate the ambient Hopf algebra. -/
theorem coordinateBialgHom_surjective_iff (b : Basis (Fin n) R M) :
    Function.Surjective (coordinateBialgHom (H := H) b) ↔
      matrixCoefficientSubalgebraWithAntipode (R := R) (H := H) (M := M) = ⊤ := by
  rw [← BialgHom.coe_toAlgHom, ← AlgHom.range_eq_top, coordinateBialgHom_range]

end Coordinate

end

end TauCeti.Comodule
