/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Scheme
public import TauCeti.Algebra.AlgebraicGroup.Representation.Coordinate

/-!
# Faithful finite free representations of affine group schemes

Let `M` be a finite free right comodule over a commutative Hopf algebra `H`. A choice of basis
gives the coordinate morphism

```text
O(GL(M)) ⟶ H
```

and hence, contravariantly, a morphism from the affine group scheme represented by `H` to
`GL(M)`. This file defines the representation to be faithful when that group-scheme morphism is a
closed immersion and proves the matrix-coefficient criterion: faithfulness is equivalent to the
coefficients of `M` and its dual generating `H` as an algebra.

The dual coefficients cannot be omitted. The coordinate ring of `GL(M)` is generated by the
generic matrix entries together with their antipode images, which map respectively to the
coefficients of `M` and its dual. Equivalently, the image of the coordinate morphism is the
coefficient algebra of the product comodule `M × Mᵛ`.

Mathlib's current `hopfSpec` construction requires the base ring and Hopf-algebra carrier to
lie in the same universe. The comodule carrier remains universe-polymorphic.

## Main declarations

* `TauCeti.Comodule.matrixCoefficientSubalgebraWithAntipode_eq_prod_dual`: coefficients and
  their antipode images generate the coefficient algebra of `M × Mᵛ`.
* `TauCeti.Comodule.coordinateHom`: the bundled coordinate Hopf-algebra morphism.
* `TauCeti.Comodule.groupSchemeMap`: the group-scheme morphism associated to a based comodule.
* `TauCeti.Comodule.IsFaithful`: faithfulness as a closed immersion into `GL(M)`.
* `TauCeti.Comodule.isFaithful_iff_matrixCoefficientSubalgebraWithAntipode_eq_top`: the
  group-scheme form of the criterion.
* `TauCeti.Comodule.isFaithful_basis_independent`: faithfulness is independent of the basis and
  its finite index type.

## References

This is the faithful-representation criterion of J. S. Milne, *Algebraic Groups* (2017),
Remark 4.1 and Theorems 4.9 and 4.14. It advances `ReductiveGroups/README.md`, Layer 1,
"Faithfulness done right".
-/

public section

open CategoryTheory
open Module

namespace TauCeti.Comodule

universe u v w

noncomputable section

section Scheme

variable {R H : Type u} {M : Type w}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]
variable {n : ℕ}

/-- The morphism of commutative Hopf algebras associated to a based finite free comodule. -/
noncomputable def coordinateHom (b : Basis (Fin n) R M) :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ _root_.CommHopfAlgCat.of R H :=
  _root_.CommHopfAlgCat.ofHom (coordinateBialgHom (H := H) b)

/-- The underlying bialgebra morphism of `coordinateHom` is the coordinate morphism. -/
@[simp]
theorem hom_coordinateHom (b : Basis (Fin n) R M) :
    (coordinateHom (H := H) b).hom = coordinateBialgHom (H := H) b :=
  by rw [coordinateHom, CommHopfAlgCat.hom_ofHom]

/-- The group-scheme morphism from the affine group represented by `H` to `GLₙ` associated to a
comodule with a basis indexed by `Fin n`. -/
noncomputable def groupSchemeMap (b : Basis (Fin n) R M) :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of R)).obj
        (Opposite.op (_root_.CommHopfAlgCat.of R H)) ⟶ GeneralLinear.groupScheme R n :=
  GeneralLinear.groupSchemeMap R n (coordinateHom (H := H) b)

/-- The representation map is the general-linear group-scheme map induced by its coordinate
Hopf-algebra morphism. -/
theorem groupSchemeMap_def (b : Basis (Fin n) R M) :
    groupSchemeMap (H := H) b =
      GeneralLinear.groupSchemeMap R n (coordinateHom (H := H) b) :=
  by rw [groupSchemeMap]

/-- Under the canonical spectrum presentations, the underlying scheme morphism of the
representation is induced by its coordinate Hopf-algebra morphism.

This is a heterogeneous equality because the spectrum presentations change the endpoint types
of the scheme morphism. -/
theorem groupSchemeMap_hom_left (b : Basis (Fin n) R M) :
    (groupSchemeMap (H := H) b).hom.hom.left ≍
      AlgebraicGeometry.Spec.map (CommRingCat.ofHom
        (coordinateHom (H := H) b).hom.toAlgHom.toRingHom) := by
  unfold groupSchemeMap
  exact GeneralLinear.groupSchemeMap_hom_left R n (coordinateHom (H := H) b)

/-- A based finite free comodule is faithful when its associated morphism into the general linear
group scheme is a closed immersion. -/
def IsFaithful (b : Basis (Fin n) R M) : Prop :=
  AlgebraicGeometry.IsClosedImmersion (groupSchemeMap (H := H) b).hom.hom.left

/-- Faithfulness means that the group-scheme morphism associated to the based comodule is a
closed immersion. -/
theorem isFaithful_def (b : Basis (Fin n) R M) :
    IsFaithful (H := H) b ↔
      AlgebraicGeometry.IsClosedImmersion (groupSchemeMap (H := H) b).hom.hom.left :=
  Iff.rfl

/-- A based finite free comodule is faithful exactly when the coefficients of the comodule and
its dual generate the ambient Hopf algebra. -/
theorem isFaithful_iff_matrixCoefficientSubalgebraWithAntipode_eq_top
    (b : Basis (Fin n) R M) :
    IsFaithful (H := H) b ↔
      matrixCoefficientSubalgebraWithAntipode (R := R) (H := H) (M := M) = ⊤ := by
  rw [isFaithful_def, groupSchemeMap_def,
    GeneralLinear.isClosedImmersion_groupSchemeMap_iff,
    ← BialgHom.coe_toAlgHom,
    hom_coordinateHom,
    ← AlgHom.range_eq_top,
    coordinateBialgHom_range]

/-- Faithfulness is independent of the chosen finite basis and its index cardinality. -/
theorem isFaithful_basis_independent {m : ℕ}
    (b : Basis (Fin n) R M) (b' : Basis (Fin m) R M) :
    IsFaithful (H := H) b ↔ IsFaithful (H := H) b' := by
  rw [isFaithful_iff_matrixCoefficientSubalgebraWithAntipode_eq_top,
    isFaithful_iff_matrixCoefficientSubalgebraWithAntipode_eq_top]

end Scheme

end

end TauCeti.Comodule
