/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Scheme
public import TauCeti.Algebra.AlgebraicGroup.Representation.Coordinate
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Dual
public import TauCeti.AlgebraicGeometry.AffineGroupScheme.ClosedImmersion

/-!
# Faithful finite free representations of affine group schemes

Let `M` be a finite free right comodule over a commutative Hopf algebra `H`. A choice of basis
gives the coordinate morphism

```text
O(GL(M)) ⟶ H
```

and hence, contravariantly, a morphism from the affine group scheme represented by `H` to
`GL(M)`. This file defines the representation to be faithful when that group-scheme morphism is a
closed immersion and proves the matrix-coefficient criterion: faithfulness is equivalent to the
coefficients of `M` and its dual generating `H` as an algebra.

The dual coefficients cannot be omitted. The coordinate ring of `GL(M)` is generated by the
generic matrix entries together with their antipode images, which map respectively to the
coefficients of `M` and its dual. Equivalently, the image of the coordinate morphism is the
coefficient algebra of the product comodule `M × Mᵛ`.

## Main declarations

* `TauCeti.Comodule.matrixCoefficientSubalgebraWithDual`: the algebra generated by the
  coefficients and their antipode images, equivalently the coefficients of `M × Mᵛ`.
* `TauCeti.Comodule.coordinateBialgHom_range`: this algebra is the image of the coordinate
  morphism.
* `TauCeti.Comodule.coordinateBialgHom_surjective_iff`: the algebraic matrix-coefficient
  criterion.
* `TauCeti.Comodule.groupSchemeMap`: the group-scheme morphism associated to a based comodule.
* `TauCeti.Comodule.IsFaithful`: faithfulness as a closed immersion into `GL(M)`.
* `TauCeti.Comodule.isFaithful_iff_matrixCoefficientSubalgebraWithDual_eq_top`: the
  group-scheme form of the criterion.

## References

This is the faithful-representation criterion of J. S. Milne, *Algebraic Groups* (2017),
Remark 4.1 and Theorems 4.9 and 4.14. It advances `ReductiveGroups/README.md`, Layer 1,
"Faithfulness done right".
-/

public section

open CategoryTheory
open Module

namespace TauCeti.Comodule

universe u v w

noncomputable section

section Range

variable {R : Type u} {H : Type v} {M : Type w}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]
variable {n : ℕ}

attribute [local instance] dual Prod

/-- The algebra generated by the matrix coefficients of a comodule and their antipode images.

For a finite projective comodule, `matrixCoefficientSubalgebraWithDual_eq_prod_dual` identifies
this intrinsically defined algebra with the coefficient algebra of `M × Mᵛ`. -/
def matrixCoefficientSubalgebraWithDual : Subalgebra R H :=
  matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ⊔
    (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
      (HopfAlgebra.antipodeAlgHom R H)

/-- The algebra generated by the coefficients and their antipode images is their supremum. -/
theorem matrixCoefficientSubalgebraWithDual_def :
    matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) =
      matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ⊔
        (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
          (HopfAlgebra.antipodeAlgHom R H) := by
  rfl

/-- Every coefficient-matrix entry belongs to the algebra generated by the coefficients and
their antipode images. -/
theorem coefficientMatrix_mem_matrixCoefficientSubalgebraWithDual
    (b : Basis (Fin n) R M) (i j : Fin n) :
    coefficientMatrix (C := H) b i j ∈
      matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) := by
  rw [matrixCoefficientSubalgebraWithDual_def, coefficientMatrix_apply]
  apply (le_sup_left : matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ≤ _)
  exact matrixCoefficient_mem_subalgebra (R := R) (C := H) (b.coord i) (b j)

/-- The antipode of every coefficient-matrix entry belongs to the algebra generated by the
coefficients and their antipode images. -/
theorem antipode_coefficientMatrix_mem_matrixCoefficientSubalgebraWithDual
    (b : Basis (Fin n) R M) (i j : Fin n) :
    HopfAlgebra.antipode R (coefficientMatrix (C := H) b i j) ∈
      matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) := by
  rw [matrixCoefficientSubalgebraWithDual_def]
  apply (le_sup_right :
    (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
      (HopfAlgebra.antipodeAlgHom R H) ≤ _)
  exact ⟨coefficientMatrix (C := H) b i j,
    by rw [coefficientMatrix_apply]
       exact matrixCoefficient_mem_subalgebra (R := R) (C := H) (b.coord i) (b j), rfl⟩

/-- For a finite projective comodule, adjoining the antipode images of its coefficients is the
same as taking the coefficient algebra of the product with its dual. -/
theorem matrixCoefficientSubalgebraWithDual_eq_prod_dual
    [Module.Finite R M] [Module.Projective R M] :
    matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) =
      matrixCoefficientSubalgebra (R := R) (C := H) (M := M × Module.Dual R M) := by
  rw [matrixCoefficientSubalgebraWithDual, matrixCoefficientSubalgebra_prod_dual]

/-- The image of the coordinate morphism of a based finite free comodule is exactly the algebra
generated by its coefficients and their antipode images.

The original coefficients are the images of the generic matrix entries, while the dual
coefficients are their antipode images. -/
theorem coordinateBialgHom_range (b : Basis (Fin n) R M) :
    (coordinateBialgHom (H := H) b).toAlgHom.range =
      matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) := by
  classical
  apply le_antisymm
  · rw [← Algebra.map_top,
      ← GeneralLinear.adjoin_coordinateHopfAlgebra_X_union_antipode_X,
      AlgHom.map_adjoin]
    apply Algebra.adjoin_le
    rintro _ ⟨_, ⟨⟨i, j⟩, rfl⟩ | ⟨⟨i, j⟩, rfl⟩, rfl⟩
    · rw [BialgHom.coe_toAlgHom, coordinateBialgHom_X]
      exact coefficientMatrix_mem_matrixCoefficientSubalgebraWithDual (H := H) b i j
    · rw [BialgHom.coe_toAlgHom, BialgHomClass.map_antipode, coordinateBialgHom_X]
      exact antipode_coefficientMatrix_mem_matrixCoefficientSubalgebraWithDual (H := H) b i j
  · rw [matrixCoefficientSubalgebraWithDual_def]
    apply sup_le
    · rw [← adjoin_coefficientMatrixSet b]
      apply Algebra.adjoin_le
      intro c hc
      obtain ⟨i, j, rfl⟩ := (mem_coefficientMatrixSet_iff (C := H) b c).mp hc
      apply (AlgHom.mem_range
        (φ := (coordinateBialgHom (H := H) b).toAlgHom)).mpr
      refine ⟨GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
        (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j))), ?_⟩
      exact coordinateBialgHom_X (H := H) b i j
    · rw [← adjoin_coefficientMatrixSet b, AlgHom.map_adjoin]
      apply Algebra.adjoin_le
      intro c hc
      obtain ⟨d, hd, rfl⟩ := hc
      obtain ⟨i, j, rfl⟩ := (mem_coefficientMatrixSet_iff (C := H) b d).mp hd
      apply (AlgHom.mem_range
        (φ := (coordinateBialgHom (H := H) b).toAlgHom)).mpr
      refine ⟨GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
        ((GeneralLinear.localizedGenericMatrix R n)⁻¹ i j), ?_⟩
      simpa only [BialgHom.coe_toAlgHom, HopfAlgebra.antipodeAlgHom_apply] using
        coordinateBialgHom_antipode_X (H := H) b i j

/-- The coordinate morphism is surjective exactly when the coefficients of the comodule and its
dual generate the ambient Hopf algebra. -/
theorem coordinateBialgHom_surjective_iff (b : Basis (Fin n) R M) :
    Function.Surjective (coordinateBialgHom (H := H) b) ↔
      matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) = ⊤ := by
  rw [← BialgHom.coe_toAlgHom, ← AlgHom.range_eq_top, coordinateBialgHom_range]

end Range

section Scheme

variable {R H M : Type u}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]
variable {n : ℕ}

/-- The morphism of commutative Hopf algebras associated to a based finite free comodule. -/
noncomputable def coordinateHom (b : Basis (Fin n) R M) :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ _root_.CommHopfAlgCat.of R H :=
  _root_.CommHopfAlgCat.ofHom (coordinateBialgHom (H := H) b)

/-- The underlying bialgebra morphism of `coordinateHom` is the coordinate morphism. -/
@[simp]
theorem coordinateHom_hom (b : Basis (Fin n) R M) :
    (coordinateHom (H := H) b).hom = coordinateBialgHom (H := H) b :=
  by rw [coordinateHom, CommHopfAlgCat.hom_ofHom]

/-- The group-scheme morphism from the affine group represented by `H` to `GLₙ` associated to a
comodule with a basis indexed by `Fin n`. -/
noncomputable def groupSchemeMap (b : Basis (Fin n) R M) :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of R)).obj
        (Opposite.op (_root_.CommHopfAlgCat.of R H)) ⟶ GeneralLinear.groupScheme R n :=
  GeneralLinear.groupSchemeMap R n (coordinateHom (H := H) b)

/-- The representation map is the general-linear group-scheme map induced by its coordinate
Hopf-algebra morphism. -/
theorem groupSchemeMap_def (b : Basis (Fin n) R M) :
    groupSchemeMap (H := H) b =
      GeneralLinear.groupSchemeMap R n (coordinateHom (H := H) b) :=
  by rw [groupSchemeMap]

/-- A based finite free comodule is faithful when its associated morphism into the general linear
group scheme is a closed immersion. -/
def IsFaithful (b : Basis (Fin n) R M) : Prop :=
  AlgebraicGeometry.IsClosedImmersion (groupSchemeMap (H := H) b).hom.hom.left

/-- Faithfulness means that the group-scheme morphism associated to the based comodule is a
closed immersion. -/
theorem isFaithful_def (b : Basis (Fin n) R M) :
    IsFaithful (H := H) b ↔
      AlgebraicGeometry.IsClosedImmersion (groupSchemeMap (H := H) b).hom.hom.left :=
  Iff.rfl

/-- A based finite free comodule is faithful exactly when the coefficients of the comodule and
its dual generate the ambient Hopf algebra. -/
theorem isFaithful_iff_matrixCoefficientSubalgebraWithDual_eq_top
    (b : Basis (Fin n) R M) :
    IsFaithful (H := H) b ↔
      matrixCoefficientSubalgebraWithDual (R := R) (H := H) (M := M) = ⊤ := by
  rw [isFaithful_def, groupSchemeMap_def,
    GeneralLinear.isClosedImmersion_groupSchemeMap_iff,
    ← BialgHom.coe_toAlgHom,
    coordinateHom_hom,
    ← AlgHom.range_eq_top,
    coordinateBialgHom_range]

/-- Faithfulness is independent of the chosen `Fin n`-indexed basis. -/
theorem isFaithful_basis_independent (b b' : Basis (Fin n) R M) :
    IsFaithful (H := H) b ↔ IsFaithful (H := H) b' := by
  rw [isFaithful_iff_matrixCoefficientSubalgebraWithDual_eq_top,
    isFaithful_iff_matrixCoefficientSubalgebraWithDual_eq_top]

end Scheme

end

end TauCeti.Comodule
