/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Scheme
public import TauCeti.Algebra.AlgebraicGroup.Representation.Coordinate

/-!
# Faithful finite free representations of affine group schemes

Let `M` be a finite free right comodule over a commutative Hopf algebra `H`. A choice of basis
gives the coordinate morphism

```text
O(GL(M)) ⟶ H
```

and hence, contravariantly, a morphism from the affine group scheme represented by `H` to
`GL(M)`. This file defines the representation to be faithful when the coefficients of `M` and
its dual generate `H` as an algebra, and proves that for every finite basis this is equivalent to
the associated group-scheme morphism being a closed immersion.

The dual coefficients cannot be omitted. The coordinate ring of `GL(M)` is generated by the
generic matrix entries together with their antipode images, which map respectively to the
coefficients of `M` and its dual. Equivalently, the image of the coordinate morphism is the
coefficient algebra of the product comodule `M × Mᵛ`.

Mathlib's current `hopfSpec` construction requires the base ring and Hopf-algebra carrier to
lie in the same universe. The comodule carrier remains universe-polymorphic.

## Main declarations

* `TauCeti.Comodule.coordinateHom`: the bundled coordinate Hopf-algebra morphism.
* `TauCeti.Comodule.groupSchemeMap`: the group-scheme morphism associated to a based comodule.
* `TauCeti.Comodule.IsFaithful`: basis-free faithfulness via coefficient generation.
* `TauCeti.Comodule.isFaithful_iff_isClosedImmersion_groupSchemeMap`: the group-scheme form of
  the criterion for every finite basis.

## References

This is the faithful-representation criterion of J. S. Milne, *Algebraic Groups* (2017),
Remark 4.1 and Theorem 4.9. It advances `ReductiveGroups/README.md`, Layer 1,
"Faithfulness done right".
-/

public section

open CategoryTheory
open Module

namespace TauCeti.Comodule

universe u v w

noncomputable section

section Faithful

variable {R : Type u} {H : Type v} {M : Type w}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]

/-- A finite free comodule is faithful when its coefficients and their antipode images generate
the ambient Hopf algebra. The theorem `isFaithful_iff_isClosedImmersion_groupSchemeMap` identifies
this intrinsic condition with the associated group-scheme morphism being a closed immersion for
every finite basis. -/
def IsFaithful [Module.Free R M] [Module.Finite R M] : Prop :=
  matrixCoefficientSubalgebraWithAntipode (R := R) (H := H) (M := M) = ⊤

end Faithful

section Scheme

variable {R H : Type u} {M : Type w}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]
variable {n : ℕ}

/-- The morphism of commutative Hopf algebras associated to a based finite free comodule. -/
noncomputable def coordinateHom (b : Basis (Fin n) R M) :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ _root_.CommHopfAlgCat.of R H :=
  _root_.CommHopfAlgCat.ofHom (coordinateBialgHom (H := H) b)

/-- The underlying bialgebra morphism of `coordinateHom` is the coordinate morphism. -/
@[simp]
theorem hom_coordinateHom (b : Basis (Fin n) R M) :
    (coordinateHom (H := H) b).hom = coordinateBialgHom (H := H) b :=
  by rw [coordinateHom, CommHopfAlgCat.hom_ofHom]

/-- The group-scheme morphism from the affine group represented by `H` to `GLₙ` associated to a
comodule with a basis indexed by `Fin n`. -/
noncomputable def groupSchemeMap (b : Basis (Fin n) R M) :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of R)).obj
        (Opposite.op (_root_.CommHopfAlgCat.of R H)) ⟶ GeneralLinear.groupScheme R n :=
  GeneralLinear.groupSchemeMap R n (coordinateHom (H := H) b)

/-- A finite free comodule is faithful exactly when the group-scheme morphism associated to any
finite basis is a closed immersion. -/
theorem isFaithful_iff_isClosedImmersion_groupSchemeMap [Module.Free R M] [Module.Finite R M]
    (b : Basis (Fin n) R M) :
    IsFaithful (R := R) (H := H) (M := M) ↔
      AlgebraicGeometry.IsClosedImmersion (groupSchemeMap (H := H) b).hom.hom.left := by
  unfold IsFaithful groupSchemeMap
  rw [GeneralLinear.isClosedImmersion_groupSchemeMap_iff,
    hom_coordinateHom,
    coordinateBialgHom_surjective_iff]

end Scheme

end

end TauCeti.Comodule
