/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Spectrum.Prime.Topology
public import Mathlib.Topology.Connected.LocallyConnected

/-!
# The idempotent cutting out a connected component

When `Spec R` is locally connected, the connected component of a point `x` is clopen. The
idempotent--clopen correspondence therefore supplies a canonical idempotent `eₓ : R` whose basic
open is that component. Equivalently, the ideal `(1 - eₓ)` cuts out the component as a closed
subset, and the spectrum of `R / (1 - eₓ)` is homeomorphic to it.

The construction is stated under the natural topological hypothesis
`LocallyConnectedSpace (PrimeSpectrum R)`. In particular it applies to Noetherian rings, for which
Tau Ceti already supplies the locally connected instance.

## Main declarations

* `PrimeSpectrum.connectedComponentIdempotent`: the idempotent selecting the component of a point.
* `PrimeSpectrum.connectedComponentIdeal`: the ideal generated by its complementary idempotent.
* `PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent`: the spectrum of the quotient
  by that ideal is the selected connected component.

## References

* The Stacks Project, Tag 00EE, for the idempotent--clopen correspondence.
* J. S. Milne, *Algebraic Groups* (2017), Section 2.a, for the identity-component construction.

This is the commutative-algebra input for the identity component in Layer 3 of the
ReductiveGroups roadmap.
-/

public section

open Set Topology

namespace PrimeSpectrum

universe u

variable {R : Type u} [CommRing R] [LocallyConnectedSpace (PrimeSpectrum R)]

/-- The idempotent whose basic open is the connected component of `x` in `Spec R`.

It is the inverse image of the clopen connected component under Mathlib's order equivalence
between idempotents and clopen subsets of the prime spectrum. -/
noncomputable def connectedComponentIdempotent (x : PrimeSpectrum R) : R :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).1

/-- The element selecting a connected component is idempotent. -/
theorem isIdempotentElem_connectedComponentIdempotent (x : PrimeSpectrum R) :
    IsIdempotentElem (connectedComponentIdempotent x) :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).2

/-- The basic open of the component idempotent is exactly the connected component. -/
theorem basicOpen_connectedComponentIdempotent (x : PrimeSpectrum R) :
    (basicOpen (connectedComponentIdempotent x) : Set (PrimeSpectrum R)) =
      connectedComponent x := by
  simpa only [connectedComponentIdempotent, TopologicalSpace.Clopens.toOpens,
    TopologicalSpace.Opens.coe_mk, TopologicalSpace.Clopens.coe_mk] using congrArg SetLike.coe
      (basicOpen_isIdempotentElemEquivClopens_symm
        (⟨connectedComponent x, isClopen_connectedComponent⟩ :
          TopologicalSpace.Clopens (PrimeSpectrum R)))

/-- The component idempotent does not belong to the prime ideal defining the selected point. -/
theorem connectedComponentIdempotent_notMem (x : PrimeSpectrum R) :
    connectedComponentIdempotent x ∉ x.asIdeal := by
  apply (mem_basicOpen _ _).mp
  -- `mem_basicOpen` uses an `Opens` membership, while the characteristic lemma uses its set.
  change x ∈ (basicOpen (connectedComponentIdempotent x) : Set (PrimeSpectrum R))
  rw [basicOpen_connectedComponentIdempotent]
  exact mem_connectedComponent

/-- An idempotent is the component idempotent exactly when its basic open is the selected
connected component. -/
theorem eq_connectedComponentIdempotent_iff {e : R} (he : IsIdempotentElem e)
    (x : PrimeSpectrum R) :
    e = connectedComponentIdempotent x ↔
      (basicOpen e : Set (PrimeSpectrum R)) = connectedComponent x := by
  constructor
  · rintro rfl
    exact basicOpen_connectedComponentIdempotent x
  · intro h
    apply basicOpen_injOn_isIdempotentElem he
      (isIdempotentElem_connectedComponentIdempotent x)
    exact TopologicalSpace.Opens.ext
      (h.trans (basicOpen_connectedComponentIdempotent x).symm)

/-- If the whole prime spectrum is connected, its component idempotent is one. -/
@[simp]
theorem connectedComponentIdempotent_eq_one [ConnectedSpace (PrimeSpectrum R)]
    (x : PrimeSpectrum R) : connectedComponentIdempotent x = 1 := by
  symm
  apply (eq_connectedComponentIdempotent_iff IsIdempotentElem.one x).mpr
  simp only [basicOpen_one, TopologicalSpace.Opens.coe_top]
  exact (PreconnectedSpace.connectedComponent_eq_univ x).symm

/-- The ideal generated by the complementary idempotent `1 - eₓ`. Its zero locus is the
connected component of `x`. -/
noncomputable def connectedComponentIdeal (x : PrimeSpectrum R) : Ideal R :=
  Ideal.span {1 - connectedComponentIdempotent x}

/-- The component ideal is the principal ideal generated by the complementary idempotent. -/
@[simp]
theorem connectedComponentIdeal_eq_span (x : PrimeSpectrum R) :
    connectedComponentIdeal x = Ideal.span {1 - connectedComponentIdempotent x} :=
  (rfl)

/-- The zero locus of the component ideal is exactly the connected component of the point. -/
theorem zeroLocus_connectedComponentIdeal (x : PrimeSpectrum R) :
    zeroLocus (connectedComponentIdeal x : Set R) = connectedComponent x := by
  rw [connectedComponentIdeal, zeroLocus_span,
    zeroLocus_eq_basicOpen_of_isIdempotentElem _
      (isIdempotentElem_connectedComponentIdempotent x).one_sub,
    sub_sub_cancel, basicOpen_connectedComponentIdempotent]

/-- The component ideal is contained in the prime ideal defining the selected point. -/
theorem connectedComponentIdeal_le (x : PrimeSpectrum R) :
    connectedComponentIdeal x ≤ x.asIdeal := by
  rw [← SetLike.coe_subset_coe, ← mem_zeroLocus,
    zeroLocus_connectedComponentIdeal]
  exact mem_connectedComponent

/-- The image of the spectrum of the component quotient is the selected component. -/
theorem range_comap_quotientMk_connectedComponentIdeal (x : PrimeSpectrum R) :
    Set.range (comap (Ideal.Quotient.mk (connectedComponentIdeal x))) =
      connectedComponent x := by
  rw [range_comap_of_surjective _ _ Ideal.Quotient.mk_surjective,
    Ideal.mk_ker, zeroLocus_connectedComponentIdeal]

/-- **The spectrum of `R / (1 - eₓ)` is homeomorphic to the connected component of `x`.**

The homeomorphism is induced by contraction along the quotient map. -/
noncomputable def primeSpectrumQuotientHomeomorphConnectedComponent
    (x : PrimeSpectrum R) :
    PrimeSpectrum (R ⧸ connectedComponentIdeal x) ≃ₜ
      (connectedComponent x : Set (PrimeSpectrum R)) :=
  (isEmbedding_comap_of_surjective
      (R ⧸ connectedComponentIdeal x)
      (Ideal.Quotient.mk (connectedComponentIdeal x))
      Ideal.Quotient.mk_surjective).toHomeomorph.trans
    (Homeomorph.setCongr (range_comap_quotientMk_connectedComponentIdeal x))

@[simp]
theorem primeSpectrumQuotientHomeomorphConnectedComponent_apply
    (x : PrimeSpectrum R) (y : PrimeSpectrum (R ⧸ connectedComponentIdeal x)) :
    (primeSpectrumQuotientHomeomorphConnectedComponent x y : PrimeSpectrum R) =
      comap (Ideal.Quotient.mk (connectedComponentIdeal x)) y :=
  (rfl)

end PrimeSpectrum
