/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.RingTheory.Etale.Basic
public import Mathlib.RingTheory.Localization.Away.Lemmas

/-!
# Étale quotients by idempotents

The quotient of a commutative ring by an idempotent-generated ideal is étale over the
ring. This applies to the coordinate algebras of clopen subschemes, including connected
components when the prime spectrum is locally connected.

## References

* The Stacks Project, Section 10.143, Étale ring maps.
-/

public section

namespace TauCeti

/-- A quotient by an ideal generated by an idempotent is étale over the original ring. -/
theorem etale_quotient_span_of_isIdempotentElem {R : Type*} [CommRing R] {e : R}
    (he : IsIdempotentElem e) : Algebra.Etale R (R ⧸ Ideal.span {e}) := by
  let : IsLocalization.Away (1 - e) (R ⧸ Ideal.span {e}) := by
    have h := IsLocalization.Away.quotient_of_isIdempotentElem he.one_sub
    rw [sub_sub_cancel] at h
    exact h
  exact Algebra.Etale.of_isLocalizationAway (1 - e)

end TauCeti
