/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.RingTheory.Etale.Basic

/-!
# Étale quotients by idempotents

The quotient of a commutative ring by an idempotent-generated ideal is étale over the
ring. This applies to the coordinate algebras of clopen subschemes, including connected
components when the prime spectrum is locally connected.

The proof uses Mathlib's `Algebra.FormallyEtale.iff_of_surjective` and finite presentation
of quotients by finitely generated ideals.

## References

* The Stacks Project, Section 10.143, Étale ring maps.
-/

public section

namespace TauCeti

/-- A quotient by an ideal generated by an idempotent is étale over the original ring. -/
theorem etale_quotient_span_of_isIdempotentElem {R : Type*} [CommRing R] {e : R}
    (he : IsIdempotentElem e) : Algebra.Etale R (R ⧸ Ideal.span {e}) := by
  refine { formallyEtale := ?_, finitePresentation := ?_ }
  · apply (Algebra.FormallyEtale.iff_of_surjective Ideal.Quotient.mk_surjective).mpr
    rw [Ideal.Quotient.algebraMap_eq, Ideal.mk_ker]
    simp only [IsIdempotentElem, Ideal.span_singleton_mul_span_singleton, he.eq]
  · exact Algebra.FinitePresentation.quotient (Submodule.fg_span_singleton _)

end TauCeti
