/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.AlgebraicGroup.FiniteType.ConnectedComponents
public import TauCeti.Algebra.AlgebraicGroup.Tangent.Scheme
public import TauCeti.RingTheory.Idempotents.ConnectedComponent

/-!
# The coordinate idempotent of the identity component

Let `H` be a finite-type commutative bialgebra over a field. Its counit defines the identity point
of `Spec H`. Since `H` is Noetherian, that point has a clopen connected component, selected by a
canonical idempotent `e⁰ ∈ H`. The principal ideal `(1 - e⁰)` cuts out precisely this
component, and its quotient spectrum is homeomorphic to the identity component.

This file constructs the coordinate-ring carrier of the identity component. It does not yet claim
that `(1 - e⁰)` is a Hopf ideal: proving compatibility with comultiplication and antipode, and
then transporting the result to affine group schemes, is the next step of the Layer 3 milestone.

## Main declarations

* `Bialgebra.identityComponentIdempotent`: the idempotent selecting the component of the identity.
* `Bialgebra.identityComponentIdeal`: the principal ideal `(1 - e⁰)` cutting it out.
* `Bialgebra.primeSpectrumIdentityComponentHomeomorph`: the quotient spectrum is the identity
  component.
* `Bialgebra.identityComponentCounitAlgHom`: the identity point factors through the quotient.

## References

* J. S. Milne, *Algebraic Groups* (2017), Section 2.a.
* The Stacks Project, Tags 00EE and 022R.

This advances Layer 3, "Identity component `G°` and component group `π₀(G)`", of the
ReductiveGroups roadmap.
-/

public section

open AlgebraicGeometry

namespace TauCeti.Bialgebra

universe u

variable (k : Type u) [Field k]
variable (H : Type u) [CommRing H] [Bialgebra k H] [Algebra.FiniteType k H]

/-- The idempotent in the coordinate ring whose basic open is the connected component of the
identity point. -/
noncomputable abbrev identityComponentIdempotent : H :=
  letI : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  PrimeSpectrum.connectedComponentIdempotent (augmentationPoint k H)

/-- The coordinate idempotent of the identity component is idempotent. -/
theorem isIdempotentElem_identityComponentIdempotent :
    IsIdempotentElem (identityComponentIdempotent k H) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  exact PrimeSpectrum.isIdempotentElem_connectedComponentIdempotent (augmentationPoint k H)

/-- The basic open of the identity-component idempotent is the connected component of the
identity point. -/
theorem basicOpen_identityComponentIdempotent :
    (PrimeSpectrum.basicOpen (identityComponentIdempotent k H) : Set (PrimeSpectrum H)) =
      connectedComponent (augmentationPoint k H) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  exact PrimeSpectrum.basicOpen_connectedComponentIdempotent (augmentationPoint k H)

/-- The counit takes the identity-component idempotent to one. -/
@[simp]
theorem counit_identityComponentIdempotent :
    Coalgebra.counit (R := k) (A := H) (identityComponentIdempotent k H) = 1 := by
  have hnot : identityComponentIdempotent k H ∉ (augmentationPoint k H).asIdeal := by
    let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
    exact PrimeSpectrum.connectedComponentIdempotent_notMem (augmentationPoint k H)
  rw [augmentationPoint, AlgHom.kernelPoint_asIdeal, RingHom.mem_ker] at hnot
  have hnot' : (_root_.Bialgebra.counitAlgHom k H).toLinearMap
      (identityComponentIdempotent k H) ≠ 0 := hnot
  rw [_root_.Bialgebra.toLinearMap_counitAlgHom] at hnot'
  have hidempotent := (isIdempotentElem_identityComponentIdempotent k H).map
    (_root_.Bialgebra.counitAlgHom k H).toRingHom
  change IsIdempotentElem
    ((_root_.Bialgebra.counitAlgHom k H).toLinearMap
      (identityComponentIdempotent k H)) at hidempotent
  rw [_root_.Bialgebra.toLinearMap_counitAlgHom] at hidempotent
  exact (IsIdempotentElem.iff_eq_zero_or_one.mp hidempotent).resolve_left hnot'

/-- The ideal `(1 - e⁰)` whose vanishing locus is the connected component of the identity. -/
noncomputable abbrev identityComponentIdeal : Ideal H :=
  letI : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  PrimeSpectrum.connectedComponentIdeal (augmentationPoint k H)

/-- The identity-component ideal is generated by the complementary idempotent. -/
@[simp]
theorem identityComponentIdeal_eq_span :
    identityComponentIdeal k H = Ideal.span {1 - identityComponentIdempotent k H} := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  exact PrimeSpectrum.connectedComponentIdeal_eq_span (augmentationPoint k H)

/-- The zero locus of the identity-component ideal is precisely the connected component of the
identity point. -/
theorem zeroLocus_identityComponentIdeal :
    PrimeSpectrum.zeroLocus (identityComponentIdeal k H : Set H) =
      connectedComponent (augmentationPoint k H) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  exact PrimeSpectrum.zeroLocus_connectedComponentIdeal (augmentationPoint k H)

/-- The identity-component ideal is killed by the counit, so the identity point belongs to the
component quotient. -/
theorem identityComponentIdeal_le_counit_ker :
    identityComponentIdeal k H ≤
      RingHom.ker (_root_.Bialgebra.counitAlgHom k H : H →+* k) := by
  rw [identityComponentIdeal_eq_span, Ideal.span_singleton_le_iff_mem, RingHom.mem_ker]
  -- `RingHom.mem_ker` exposes the counit through its coerced ring homomorphism.
  change _root_.Bialgebra.counitAlgHom k H
      (1 - identityComponentIdempotent k H) = 0
  rw [map_sub, map_one, _root_.Bialgebra.counitAlgHom_apply,
    counit_identityComponentIdempotent, sub_self]

/-- The identity point, as an algebra homomorphism from the coordinate ring of its component. -/
noncomputable def identityComponentCounitAlgHom :
    (H ⧸ identityComponentIdeal k H) →ₐ[k] k :=
  Ideal.Quotient.liftₐ (identityComponentIdeal k H)
    (_root_.Bialgebra.counitAlgHom k H)
    (identityComponentIdeal_le_counit_ker k H)

/-- The component counit composed with the quotient map is the original counit. -/
@[simp]
theorem identityComponentCounitAlgHom_comp_mk :
    (identityComponentCounitAlgHom k H).comp
      (Ideal.Quotient.mkₐ k (identityComponentIdeal k H)) =
        _root_.Bialgebra.counitAlgHom k H :=
  Ideal.Quotient.liftₐ_comp _ _ _

/-- **The spectrum of the component quotient is homeomorphic to the connected component of the
identity.** The map to `Spec H` is contraction along the quotient map. -/
noncomputable def primeSpectrumIdentityComponentHomeomorph :
    PrimeSpectrum (H ⧸ identityComponentIdeal k H) ≃ₜ
      (connectedComponent (augmentationPoint k H) : Set (PrimeSpectrum H)) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  exact PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent
    (augmentationPoint k H)

@[simp]
theorem primeSpectrumIdentityComponentHomeomorph_apply
    (x : PrimeSpectrum (H ⧸ identityComponentIdeal k H)) :
    (primeSpectrumIdentityComponentHomeomorph k H x : PrimeSpectrum H) =
      PrimeSpectrum.comap (Ideal.Quotient.mk (identityComponentIdeal k H)) x := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  exact PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent_apply
    (augmentationPoint k H) x

end TauCeti.Bialgebra
